---
title: "Turmas da EBD Viva"
subtitle: Escola Dominical que alcança VIDAS
lang: pt-br
date: last-modified
date-format: DD/MM/YYYY
---

Acreditamos que a Palavra de Deus é transformadora e relevante para todas as fases da vida. Por isso, nossas turmas são organizadas de forma a atender às necessidades específicas de cada faixa etária, proporcionando um ambiente acolhedor e estimulante para o crescimento espiritual. Conheça nossas turmas:

### **Crianças**

Aqui, os pequenos descobrem o amor de Deus de maneira divertida e criativa. Nossas aulas são recheadas de histórias bíblicas, atividades artísticas e músicas, criando um ambiente onde a Palavra de Deus é apresentada de forma simples e cativante. Nosso objetivo é plantar sementes de fé que florescerão ao longo da vida.

### **Adolescentes**

Os adolescentes enfrentam uma fase cheia de desafios e descobertas. Nesta turma, buscamos oferecer um espaço para reflexão e aprendizado à luz da Bíblia, ajudando-os a construir uma fé sólida e a tomar decisões alinhadas aos princípios cristãos. Os encontros são dinâmicos e incluem debates, dinâmicas e momentos de oração.

### **Jovens**

Os jovens são desafiados a viver sua fé em um mundo em constante mudança. Esta turma busca aprofundar o conhecimento bíblico e incentivar a aplicação prática dos ensinamentos de Cristo no dia a dia. Por meio de discussões interativas, estudos temáticos e convivência fraterna, os jovens são motivados a crescer como líderes espirituais e a impactar a sociedade.

### **Adultos**

Nesta turma, os adultos encontram um espaço para estudar as Escrituras de forma profunda e contextualizada. As aulas promovem reflexão, compartilhamento de experiências e edificação mútua, fortalecendo a caminhada cristã e encorajando cada participante a exercer seu papel no Reino de Deus. Os temas abordados são práticos e relevantes para o dia a dia.

### **Venha fazer parte!**

Nossas turmas estão abertas a todos que desejam aprender mais sobre a Bíblia e experimentar o amor de Deus em comunidade. Independentemente da sua idade ou experiência de fé, há um lugar especial para você na Escola Dominical. Junte-se a nós e vamos caminhemos juntos no propósito de alcançar VIDAS para Cristo!