project:
  type: website
  output-dir: docs

website:
  title: "EBD Viva"
  image: logo-ebd-viva.png
  favicon: logo-ebd-viva.png
  open-graph: true
  twitter-card: false
  site-url: "https://ebdviva.github.io/site"
  page-navigation: true
  
  navbar:
    background: light
    logo: logo-ebd-viva.png
    logo-alt: "Logo EBD Viva"
    title: false
    collapse-below: lg
    left:
      - text: EBD Viva
        href: index.qmd
      - text: Turmas
        href: paginas/turmas/index.qmd
      - text: "Ajuda"
        menu:
          # - text: "Perguntas frequentes"
            # icon: "question-circle"
            # href: paginas/faq/faq.qmd
          - text: "Envie-nos um e-mail"
            icon: "envelope"
            href: "mailto://ebdviva@outlook.com"
  
    tools:
      - icon: instagram
        href: https://www.instagram.com/ebd.viva
        text: Instagram EBD Viva

  sidebar:
    - id: ebd-viva
      title: "EBD Viva"
      style: "floating"
      collapse-level: 2
      align: left
      contents:
        - text: "EBD Viva"
          href: index.qmd
          contents: 
            - text: "Visão de crescimento"
              href: paginas/vidas/visao-de-crescimento.qmd
            - text: "Integração estratégica"
              href: paginas/vidas/integracao-estrategica.qmd
            - text: "Discípulos em ação"
              href: paginas/vidas/discipulos-em-acao.qmd
            - text: "Aperfeiçoamento contínuo"
              href: paginas/vidas/aperfeicoamento-continuo.qmd

    - id: turmas
      title: "Turmas"
      style: "floating"
      collapse-level: 2
      align: left
      contents:
        - text: "Materiais"
          href: paginas/turmas/index.qmd
          contents:
            - text: "Adultos"
              href: paginas/turmas/adultos/index.qmd
            - text: "Jovens"
              href: paginas/turmas/jovens/index.qmd
            # - text: "Adolescentes"
              # href: paginas/turmas/adolescentes/index.qmd
            # - text: "Crianças"
              # href: paginas/turmas/criancas/index.qmd

    # - id: faq
      # title: "Perguntas Frequentes"
      # style: floating
      # collapse-level: 2
      # align: left
      # contents: 
        # - text: "Perguntas Frequentes"
          # href: paginas/faq/faq.qmd

  # bibliography: pages/publicações/bibliografia-lanal.json

format:
  html:
    toc: true
    theme:
      light: [cosmo, theme.scss]
    code-copy: true
    code-overflow: wrap
    css: styles.css
    include-after-body: js.html
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 350px

filters:
  - filters/tools-tabset.lua

freeze: true

editor: visual

profile:
  group: 
    - [prerelease,rc]

# Para inserir links para o texto bíblico do Logos
# include-after-body: 
#    - text: |
#        <script type="text/javascript">
#        var refTagger = {settings: {bibleVersion: 'bb-sbb-ntlh'}}; 
#
#        (function(d, t) {
#            var n=d.querySelector('[nonce]');
#            refTagger.settings.nonce = n && (n.nonce||n.getAttribute('nonce'));
#            var g = d.createElement(t), s = d.getElementsByTagName(t)[0];
#            g.src = 'https://api.reftagger.com/v2/RefTagger.js';
#            g.nonce = refTagger.settings.nonce;
#            s.parentNode.insertBefore(g, s);
#        }(document, 'script'));
#        </script>



