project:
  type: website
  output-dir: docs

website:
  title: "EBD Viva"
  navbar:
    left:
      - href: index.qmd
        text: Início
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



