---
title: Protegendo-se com integridade na sociedade
subtitle: "Lição 13"
status: arquivada
description: "A sabedoria e a integridade são virtudes do cristão que se manifestam na sociedade"
categories: 
    - Integridade
    - Sabedoria
author: Marcelo Oliveira
date: 2024-12-29
date-format: DD/MM/YYYY
lang: pt-br
---

## Texto principal

> Pv 28.12

## Leitura semanal

::: callout-tip
## Segunda - Chamado para ser sábio (Pv 1.1-6)
:::

::: callout-tip
## Terça - O que contamina o ser humano (Mc 7.20-23)
:::

::: callout-tip
## Quarta - O amor pelas coisas do mundo (1 Jo 2.15-17)
:::

::: callout-tip
## Quinta - Chamados para transformar o mundo (Mt 4.19)
:::

::: callout-tip
## Sexta - O temor do Senhor (Pv 1.7)
:::

::: callout-tip
## Sábado - Um chamado para servir (Mt 20.26-27)
:::

## Objetivos

1.  **Apresentar** a importância da sabedoria e da prudência na manutenção da ordem social
2.  **Saber** como o justo deve se portar diante dos valores opostos da sociedade
3.  **Conscientizar** de que a sabedoria e a integridade devem se manifestar externamente

## Texto bíblico

### Provérbios 28.2-12

## Introdução

## I - Sabedoria, prudência e sociedade

### 1. Sabedoria e prudência na manutenção da ordem social

::: callout-tip
## Provérbios 28.2
:::

::: callout-tip
## Provérbios 28.12
:::

### 2.Quando a injustiça prospera

::: callout-tip
## Provérbios 28.3 - a opressão domina
:::

::: callout-tip
## Provérbios 28.6 - o perverso se envaidece com suas riquezas
:::

::: callout-tip
## Provérbios 28.8 - a ganância é insaciável
:::

::: callout-tip
## Provérbios 28.11 - os ricos pensam não precisar de mais nada
:::

### 3. Quando não há compromisso com a Lei de Deus

::: callout-tip
## Provérbios 1.7
:::

::: callout-tip
## 
:::

## II - O justo diante dos valores opostos da sociedade

### 1. Diante das injustiças

### 2. Diante da corrupção moral

### 3. Tocando o mundo das pessoas

## III - Quando a sabedoria e a integridade se manifestam externamente

### 1. Vale a pena ser íntegro?

### 2. Sabedoria: amando os mandamentos de Deus?

### 3. Sabedoria e integridade para servir a sociedade

## Conclusão