---
title: "Discípulos em ação"
subtitle: "Colocando a fé em movimento."
description: _A estratégia "Discípulos em Ação" da Escola Dominical inspira e equipa os irmãos a transformarem o aprendizado bíblico em atitudes práticas de amor, serviço e evangelismo. Essas iniciativas e desafios tornam a fé relevante no dia a dia e impactam vidas dentro e fora da igreja._
author-meta: EBD Viva
date-meta: last-modified
date-format: DD/MM/YYYY
lang: pt-br
---
**Transformando aprendizado em prática**  

A essência da Escola Dominical vai além do aprendizado bíblico; ela reside na aplicação prática do que é ensinado, impulsionando os cristãos a serem luz do mundo e sal da terra. A estratégia "Discípulos em Ação" busca formar seguidores de Cristo que vivem a fé de maneira prática, impactando suas famílias, igrejas e comunidades.

### **Objetivos**  
- **Promover a prática cristã:** Inspirar os alunos a transformarem conhecimento bíblico em atitudes concretas, demonstrando amor, compaixão e serviço.  
- **Apoiar iniciativas sociais:** Incentivar projetos que alcancem os necessitados e promovam justiça social.  
- **Fomentar o evangelismo:** Encorajar o compartilhamento da mensagem de Cristo no dia a dia, com amigos, colegas e vizinhos.  

### **Como Fazer**  
- **Ações práticas regulares:** Organizar atividades missionárias e sociais, como visitas a hospitais, ações em comunidades carentes e evangelismo em áreas públicas.  
- **Testemunhos e histórias:** Promover momentos em sala de aula para que os alunos compartilhem como têm vivido os ensinamentos cristãos no cotidiano.  
- **Desafios de aplicação semanal:** Lançar desafios baseados nos estudos bíblicos para que cada participante coloque em prática uma verdade aprendida durante a semana.  

"Discípulos em Ação" reflete a convicção de que fé e obras caminham lado a lado. Cada cristão é chamado a viver como um exemplo vivo do amor de Deus, transformando sua realidade e a daqueles que estão ao seu redor.  

Junte-se a nós e torne-se um discípulo em ação!