---
title: "Visão de Crescimento"
subtitle: "Construindo um futuro de crescimento espiritual e numérico."
description: _Uma 'Visão de Crescimento' na Escola Dominical ajuda a promover o discipulado, fortalecer o ensino bíblico e alcançar mais pessoas com o Evangelho, transformando vidas e ampliando o impacto da EBD._
# author: EBD Viva
date-meta: last-modified
date-format: DD/MM/YYYY
lang: pt-br
---

O crescimento de uma Escola Dominical vai além dos números: trata-se de um impacto transformador na vida das pessoas e na comunhão da igreja. A estratégia "Visão de Crescimento" nos leva a olhar além das paredes do templo, direcionando nosso foco para o discipulado intencional e o acolhimento de novos membros.

### Nossos Objetivos:

-   **Promover o crescimento espiritual:** Ensinar a Palavra de Deus de forma relevante e prática, ajudando cada aluno a crescer na fé e no conhecimento de Cristo.\
-   **Ampliar o alcance da EBD:** Trabalhar para alcançar pessoas que ainda não participam, seja dentro ou fora da igreja.\
-   **Fortalecer o discipulado:** Formar líderes comprometidos em acompanhar, orientar e discipular novos convertidos e membros.\
-   **Conectar gerações:** Integrar crianças, adolescentes, jovens e adultos em uma visão comum de aprendizado e serviço cristão.

### Como isso acontece?

1.  **Planejamento:** Analisar continuamente as necessidades da igreja e da comunidade para criar um ambiente acolhedor e desafiador para o aprendizado.\
2.  **Eventos especiais:** Promover conferências, estudos bíblicos temáticos e atividades evangelísticas que inspiram os membros a trazerem mais pessoas para a EBD.\
3.  **Treinamento de líderes:** Capacitar professores e auxiliares é uma prioridade para que cada turma tenha um ensino de excelência.

Queremos ver vidas sendo impactadas e transformadas pelo poder do Evangelho. Junte-se a nós nessa visão!