---
title: Proteção contra os vícios
subtitle: "Lição 12"
status: atual
description: "O autodomínio é uma virtude indispensável para a superação de um vício"
categories: 
    - Vícios
author: Marcelo Oliveira
date: 2024-12-22
date-format: DD/MM/YYYY
lang: pt-br
---

## Texto principal

> Como a cidade com seus muros derrubados, assim é quem não sabe dominar-se. (Provérbios 25.28)

## Leitura semanal

::: callout-tip
## Segunda - A trágica consequência do álcool (Pv 23.29-35)

29. De quem são os ais? De quem as tristezas? E as brigas, de quem são? E os ferimentos desnecessários? De quem são os olhos vermelhos?
30. Dos que se demoram bebendo vinho, dos que andam à procura de bebida misturada.
31. Não se deixe atrair pelo vinho quando está vermelho, quando cintila no copo e escorre suavemente!
32. No fim, ele morde como serpente e envenena como víbora.
33. Seus olhos verão coisas estranhas, e sua mente imaginará coisas distorcidas.
34. Você será como quem dorme no meio do mar, como quem se deita no alto das cordas do mastro.
35. E dirá: "Espancaram-me, mas eu nada senti! Bateram em mim, mas nem percebi! Quando acordarei para que possa beber mais uma vez?
:::

::: callout-tip
## Terça - A Bíblia mostra o vício como um senhor (Rm 6.14)

Pois o pecado não os dominará, porque vocês não estão debaixo da lei, mas debaixo da graça.
:::

::: callout-tip
## Quarta - Os vícios não fazem parte do propósito de Deus para a vida (Rm 12.2)

Não se amoldem ao padrão deste mundo, mas transformem-se pela renovação da sua mente, para que sejam capazes de experimentar e comprovar a boa, agradável e perfeita vontade de Deus.
:::

::: callout-tip
## Quinta - Inclinados para as coisas do Espírito (Rm 8.5-8)

5.  Quem vive segundo a carne aspira ao que a carne deseja, mas quem vive de acordo com o Espírito aspira ao que o Espírito deseja.
6.  A aspiração da carne conduz à morte, mas a do Espírito conduz à vida e à paz;
7.  porque a aspiração da carne é inimizade contra Deus, pois não se submete à lei de Deus nem pode fazê‑lo.
8.  Quem é dominado pela carne não pode agradar a Deus.
:::

::: callout-tip
## Sexta - Andar na virtude (Ef 2.8-10)

8.  Pois pela graça vocês são salvos, por meio da fé, e isto não vem de vocês, é dom de Deus;
9.  não por obras, para que ninguém se glorie.
10. Porque fomos feitos por Deus, criados em Cristo Jesus, para boas obras, as quais Deus preparou previamente para que andássemos nelas.
:::

::: callout-tip
## Sábado - Firme na rocha (Mt 7.14)

Mas estreita é a porta e apertado é o caminho que leva à vida, e são poucos os que a encontram.
:::

## Objetivos

1.  **Apresentar** alguns conselhos a respeito dos vícios no livro de Provérbios;
2.  **Saber** as consequências que os vícios trazem;
3.  **Mostrar** como podemos nos proteger contra os vícios

## Texto bíblico

### Provérbios 20.1

> O vinho é zombador, e a bebida fermentada provoca brigas; ninguém que se deixa dominar por eles é sábio.

### Romanos 6.5-6

> 5.  Se, pois, nos tornamos unidos na semelhança da sua morte, certamente o seremos também na sua ressurreição.
> 6.  Pois sabemos que o nosso velho homem foi crucificado com ele, para que o corpo pecaminoso seja destruído, de modo que deixemos de ser escravos do pecado

## Introdução

## I - Os vícios no livro de Provérbios

### 1. Os vícios em Provérbios

::: callout-tip
## Provérbios 7.21-23 - O sábio não deve ser dominado por nenhum vício

21. Com a sedução das suas instruções o persuadiu e o atraiu com enganos sutis.
22. Imediatamente, ele a seguiu, como o boi levado ao matadouro, ou como o cervo que vai cair no laço,
23. até que uma flecha lhe atravesse o fígado, ou como o pássaro que salta para dentro do alçapão, sem saber que isso lhe custará a vida.
:::

### 2. A substância viciante (Pv 20.1)

::: callout-tip
## Provérbios 20.1

O vinho é zombador, e a bebida fermentada provoca brigas; ninguém que se deixa dominar por eles é sábio.
:::

::: callout-tip
## Provérbios 23.29-35 - O álcool produz consequências desagradáveis

29. De quem são os ais? De quem as tristezas? E as brigas, de quem são? E os ferimentos desnecessários? De quem são os olhos vermelhos?
30. Dos que se demoram bebendo vinho, dos que andam à procura de bebida misturada.
31. Não se deixe atrair pelo vinho quando está vermelho, quando cintila no copo e escorre suavemente!
32. No fim, ele morde como serpente e envenena como víbora.
33. Seus olhos verão coisas estranhas, e sua mente imaginará coisas distorcidas.
34. Você será como quem dorme no meio do mar, como quem se deita no alto das cordas do mastro.
35. E dirá: "Espancaram-me, mas eu nada senti! Bateram em mim, mas nem percebi! Quando acordarei para que possa beber mais uma vez?
:::

::: callout-tip
## Efésios 5.18

Não se embriaguem com vinho, que leva à libertinagem, mas sejam cheios com o Espírito
:::

### 3. Os demais vícios (Pv 25.28)

::: callout-tip
## Provérbios 25.28 - A importância do domínio próprio

Como a cidade com seus muros derrubados, assim é quem não sabe dominar-se.
:::

## II - O vício e suas consequências

### 1. O conceito

::: callout-tip
## Romanos 6.12-14

12. Portanto, não permitam que o pecado reine no corpo mortal de vocês, levando‑os a obedecer aos desejos malignos dele.
13. Não ofereçam os membros do corpo de vocês como instrumentos de injustiça para o pecado; antes, ofereçam‑se a Deus como quem saiu da morte para a vida; ofereçam os membros do corpo de vocês como instrumentos de justiça para Deus.
14. Assim, o pecado não deve ter domínio sobre vocês, porque vocês não estão debaixo da lei, mas debaixo da graça.
:::

### 2. Tipos diversos de vícios

### 3. Vícios presentes na vida dos jovens

## III - Protegendo-se contra os vícios

### 1. Crucificados com Cristo

::: callout-tip
## Romanos 6.5-6

5.  Se, pois, nos tornamos unidos na semelhança da sua morte, certamente o seremos também na sua ressurreição.
6.  Pois sabemos que o nosso velho homem foi crucificado com ele, para que o corpo pecaminoso seja destruído, de modo que deixemos de ser escravos do pecado
:::

::: callout-tip
## Romanos 8.5-8

5.  Quem vive segundo a carne aspira ao que a carne deseja, mas quem vive de acordo com o Espírito aspira ao que o Espírito deseja.
6.  A aspiração da carne conduz à morte, mas a do Espírito conduz à vida e à paz;
7.  porque a aspiração da carne é inimizade contra Deus, pois não se submete à lei de Deus nem pode fazê‑lo.
8.  Quem é dominado pela carne não pode agradar a Deus.
:::

::: callout-tip
## Gálatas 5.22-23

22. Entretanto, o fruto do Espírito é amor, alegria, paz, paciência, amabilidade, bondade, fidelidade,
23. mansidão e domínio próprio. Contra essas coisas não há lei.
:::

### 2. Os vícios não reinam mais

::: callout-tip
## Romanos 6.12-13

12. Portanto, não permitam que o pecado reine no corpo mortal de vocês, levando‑os a obedecer aos desejos malignos dele.
13. Não ofereçam os membros do corpo de vocês como instrumentos de injustiça para o pecado; antes, ofereçam‑se a Deus como quem saiu da morte para a vida; ofereçam os membros do corpo de vocês como instrumentos de justiça para Deus.
:::

### 3. Exercendo o autodomínio

::: callout-tip
## Efésios 2.8-10

8.  Pois pela graça vocês são salvos, por meio da fé, e isto não vem de vocês, é dom de Deus;
9.  não por obras, para que ninguém se glorie.
10. Porque fomos feitos por Deus, criados em Cristo Jesus, para boas obras, as quais Deus preparou previamente para que andássemos nelas.
:::

::: callout-tip
## Romanos 6.14

Assim, o pecado não deve ter domínio sobre vocês, porque vocês não estão debaixo da lei, mas debaixo da graça.
:::

::: callout-tip
## Provérbios 25.28

Como a cidade com os muros derrubados, assim é quem não sabe dominar‑se.
:::

::: callout-tip
## Mateus 7.24 - O prudente e o insensato

24. Portanto, quem ouve estas minhas palavras e as pratica é como o homem prudente que construiu a sua casa sobre a rocha.
:::

## Conclusão

## Slides

<div>

```{=html}
<iframe class="slide-deck" src="slides/"></iframe>
```

</div>