---
title: Autenticidade em meio às provas e tentações
subtitle: "Lição 2"
status: atual
description: "Manter a autenticidade em meio às provas e tentações é essencial para preservar nossa integridade e viver de acordo com nossos valores cristãos mais profundos"
categories: 
    - Autenticidade
    - Provas
    - Tentações
author: CPAD
date: 2025-01-12
date-format: DD/MM/YYYY
lang: pt-br
---

## Texto principal

::: callout-important
### Tiago 1.2-3

Meus irmãos, considerem motivo de grande alegria o fato de passarem por diversas provações; assim, vocês saberão que a prova da sua fé produz perseverança.
:::

## Objetivos

1.  **Compreender** a força que é produzida pelas tentações;
2.  **Explicar** o propósito das provações;
3.  **Destacar** a importância da sabedoria, proteção e confiança em Deus.

## Leitura semanal

::: callout-note
## Segunda - Gloriando-se nas tribulações

Não só isso, mas também nos gloriamos nas tribulações, porque sabemos que a tribulação produz perseverança; a perseverança, um caráter aprovado; e o caráter aprovado, esperança. (Rm 5.3-4)
:::

::: callout-note
## Terça - No mundo passaremos por aflições

Eu lhes disse essas coisas para que em mim vocês tenham paz. Neste mundo vocês terão aflições; contudo, tenham ânimo! Eu venci o mundo. (Jo 16.33)
:::

::: callout-note
## Quarta - Deus provê o escape necessário

Não sobreveio a vocês tentação que não fosse comum aos homens. E Deus é fiel; ele não permitirá que vocês sejam tentados além do que podem suportar. Mas, quando forem tentados, ele mesmo lhes providenciará um escape, para que o possam suportar. (1 Co 10.13)
:::

::: callout-note
## Quinta - A colheita é de acordo com a semeadura

Não se deixem enganar: de Deus não se zomba. Pois o que o homem semear, isso também colherá. (Gl 6.7)
:::

::: callout-note
## Sexta - A semeadura do espírito produz vida

Quem semeia para a sua carne, da carne colherá destruição; mas quem semeia para o Espírito, do Espírito colherá a vida eterna. (Gl 6.8)
:::

::: callout-note
## Sábado - A aflição produz retidão

Eu te louvarei de coração sincero quando aprender as tuas justas ordenanças. (Sl 119.7)
:::

## Leitura em classe

::: callout
## Tiago 1.12-16

12. Feliz é o homem que persevera na provação, porque depois de aprovado receberá a coroa da vida, que Deus prometeu aos que o amam.
13. Quando alguém for tentado, jamais deverá dizer: "Estou sendo tentado por Deus". Pois Deus não pode ser tentado pelo mal, e a ninguém tenta.
14. Cada um, porém, é tentado pelo próprio mau desejo, sendo por este arrastado e seduzido.
15. Então esse desejo, tendo concebido, dá à luz o pecado, e o pecado, após ter se consumado, gera a morte.
16. Meus amados irmãos, não se deixem enganar.
:::

## Sumário da lição

### Introdução

### I - A força produzida pelas tentações

1.  O que são as tentações
    -   Tg 1.3-4
    -   Mateus 4.1-11
    -   Hebreus 4.14-16
    -   1 Coríntios 10.13
2.  A procedência das tentações
    -   Tiago 1.12-15
3.  O papel do inimigo
    -   Mateus 6.13
    -   Mateus 4.3
    -   1 Tessalonicenses 3.5

### II - As provações e seus propósitos

1.  Todos os filhos de Deus são provados
2.  Prova de fé
    -   Tiago 1.3
3.  Bênção nas provações
    -   Tiago 1.12
    -   Salmos 46.1-11

### III - Sabedoria, proteção e confiança

1.  Busque a sabedoria divina
    -   Tiago 1.5
    -   Salmos 119.11
    -   1 João 4.18
    -   Romanos 8.38-39
    -   Daniel 3.17-18
2.  Proteção em meio à violência
3.  Incerteza: a marca da pós-modernidade

### IV - O cuidado com o que vemos e desejamos

1.  Atraídos pelo que vemos
    -   Tiago 1.13
    -   1 Tessalonicenses 3.5
    -   1 João 2.15-17
    -   Gênesis 3.2-9
    -   Tiago 1.15
    -   Efésios 6.11
2.  Desenvolvendo um caráter cristão
3.  Padrões modernos
4.  Como o crente deve reagir às tentações
    -   Tiago 1.16
    -   1 João 1.9
    -   1 João 1.7,9

### Conclusão