---
title: Criacionismo x Evolucionismo
subtitle: "Lição 1"
description: "Tudo foi criado por Deus"
status: atual
data: 05/01/2025
categories: 
    - Criação
author: João Paulo Mendes
date: 2025-01-05
date-format: DD/MM/YYYY
lang: pt-br
---

## A mensagem

::: {.callout}
### "Então Deus disse: - Que haja luz! E a luz começou a existir." (Gn 1.3)
:::

## Devocional

- Segunda: Gn 1.1
- Terça: Gn 2.7
- Quarta: Jó 38.1-4
- Quinta: Ne 9.6
- Sexta: Is 48.13
- Sábado: Jr 10.11-12

## Sumário da lição

### I. O ensino da criação divina

#### 1. Uma doutrina fundamental

-   Deus é o criador (Gn 1.1)
-   A criação de Deus envolve toda natureza (Gn 1.1-27)
-   O Senhor fez tudo o que desejou fazer (Sl 135.6)
-   Ninguém o aconselhou para que tomasse suas decisões (Is 40.14)

#### 2. A criação aponta para o criador

- O universo apresenta sintonia fina
- O profeta Isaías, há milhares de anos já anunciou que Deus é quem criou todas as coisas (Is 45.18)
  
#### 3. A precisão científica da Bíblia

Embora a Bíblia não tenha a intenção de ser um manual científico, é impressionante observar como ela, há milhares de anos, já tratava de temas que a ciência só veio a descobrir recentemente:

- O ciclo hidrológico (Jó 36.27-28; Ec 1.7)
- A Terra está suspensa no vazio (Jó 26.7)
- O ar é pesado (Jó 28.25)
- Tempo, espaço e matéria tiveram um começo (Gn 1.1,17,18; Jo 17.5; 1 Co 2.7)
- A Terra é uma esfera (Is 40.22)
- As estrelas são incontáveis (Jr 33.22)

### II -A teoria do evolucionismo

#### 1. O que significa

- Evolucionismo é a teoria que defende o surgimento da vida através da evolução lenta e gradativa das espécies
- Tal teoria é contrária à doutrina bíblica da Criação

#### 2. O presuposto naturalista

- O evolucionismo está apoiado no naturalismo
  - Ideia de que apenas as forças naturais operam no mundo
  - Nessa hipótese não há espaço para o sobrenatural
  - As ideias naturalistas excluem Deus de todas as suas concluções

#### 3. O evolucionismo não pode ser provado cientificamente

- O evolucionismo não deveria ser tratado como teoria, ou verdade absoluta
  - As conclusões de cientistas evolucionistas estão cheias de suposições e hipóteses não comprovadas científicamente
  - Em pontos obscuros da teoria, as conclusões são forçadas e excluem Deus
- Até hoje o evolucionismo não foi comprovado científicamente

### III - A Palavra de Deus permanece para sempre

#### 1. O evolucionismo e o registro fóssil

- Os fósseis não comprovam o evolucionismo
  - Não são encontrados fósseis que demonstrem a suposta transição de espécies
  - As pequenas alterações nas formas de vida, observadas por meio de registros fósseis não apoiam de forma robusta a teoria da evolução (Rm 1.25)

#### 2. O testemunho bíblico sobre a criação

- A criação divina relatada em Gênesis é reforçada por várias outras passagens bíblicas:
  - Salmos 102.25
  - Provérbios 3.19
  - Colossenses 1.16
  - Hebreus 1.10
  - Isaías 42.5
  - Isaías 45.12
  - Is 45.18

#### 3. A palavra de Deus sempre permanecerá

- Paulo afirmou que desde que o Pai criou o mundo, suas qualidades podem ser vistas na criação (Rm 1.20)
- Mas muitos homens se recusam a reconhecer o Senhor como Criador e não lhe dão glória; antes, são ingratos.
  - Por causa diso suas mentes estão vazias e cheias de escuridão (Rm 1.20,22)
- Apesar de todo esforço tolo do ser humano, Deus nunca deixará de ser o único e sublime Criador.
- A Palavra de Deus é verdade e permanecerá para sempre (1 Pe 1.24-25)

### Conclusão

O criacionismo bíblico é a verdade sobre a origem da vida. O Evolucionismo não se apoia em verdades científicas confiáveis. Deus criou tudo o que existe. É Ele quem mantém a natureza e a vida humana. Ele é o dono de toda a Criação (Sl 24.1).



